export const NAVIGATE_TO = 'R5_NAVIGATE';
export const CANCEL_TRANSITION = 'R5_CANCEL';
export const TRANSITION_ERROR = 'R5_TRANSITION_ERROR';
export const TRANSITION_SUCCESS = 'R5_TRANSITION_SUCCESS';
export const TRANSITION_START = 'R5_TRANSITION_START';
export const CLEAR_ERRORS = 'R5_CLEAR_ERRORS';
export const CAN_DEACTIVATE = 'R5_CAN_DEACTIVATE';
export const CAN_ACTIVATE = 'R5_CAN_ACTIVATE';
