export declare const NAVIGATE_TO = '@@router5/NAVIGATE'
export declare const CANCEL_TRANSITION = '@@router5/CANCEL'
export declare const TRANSITION_ERROR = '@@router5/TRANSITION_ERROR'
export declare const TRANSITION_SUCCESS = '@@router5/TRANSITION_SUCCESS'
export declare const TRANSITION_START = '@@router5/TRANSITION_START'
export declare const CLEAR_ERRORS = '@@router5/CLEAR_ERRORS'
export declare const CAN_DEACTIVATE = '@@router5/CAN_DEACTIVATE'
export declare const CAN_ACTIVATE = '@@router5/CAN_ACTIVATE'
